"""arqu-co repo allowlist for aggregator filtering.

Historical data under ``data/`` contains 50+ directories whose names are
worktree or branch identifiers rather than real repos. The events inside
those directories also carry the bogus name in their ``repo`` field, so
the aggregator was surfacing worktree names as repos on the dashboard.

This module loads a committed allowlist from ``data/_arqu-co-repos.json``
and exposes ``is_known_repo`` for use at event-load time. The allowlist
is regenerated by ``docs/refresh_repo_allowlist.py`` (offline-safe — falls
back to whatever was last committed).
"""

from __future__ import annotations

import json
import os
from functools import lru_cache

ALLOWLIST_FILENAME = "_arqu-co-repos.json"


@lru_cache(maxsize=8)
def load_known_repos(data_dir: str = "data") -> frozenset[str]:
    """Return the frozen set of repo names that belong to arqu-co.

    Returns an empty set when the allowlist file is missing — the caller
    should treat that as "filter disabled" rather than "everything bogus".
    """
    path = os.path.join(data_dir, ALLOWLIST_FILENAME)
    try:
        with open(path) as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return frozenset()
    return frozenset(data.get("repos") or [])


def is_known_repo(repo: str | None, data_dir: str = "data") -> bool:
    """Return True if ``repo`` is in the allowlist.

    When the allowlist is empty (file missing) every repo is accepted —
    the filter is effectively disabled, which is the safe default during
    bootstrap.
    """
    known = load_known_repos(data_dir)
    if not known:
        return True
    return repo in known
